apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_geekathon
#   backstage.io/kubernetes-id: team-xico-squad

namespace: idpkathon-dev
# namespace: team-xico-squad-idp_geekathon-dev

resources:
- ../../base
- ingress.yaml

  # ATENTION name = image.name NOT name = spec.containers[0].name
images:
- name: ghcr.io/xgeeks-geekathon/team-xico-squad
  newTag: 017da82
- name: ghcr.io/xgeeks-geekathon/team-xico-squad-datafeeder
  newTag: 017da82
